apiVersion: jib/v1alpha1
kind: BuildFile

from:
  image: "nginx:latest"  # 베이스 이미지로 nginx 사용

format: Docker  # Docker 형식으로 이미지 빌드

# 레이어 설정
layers:
  entries:
    - name: "app-build"  # 첫 번째 레이어는 빌드된 React 앱 파일들
      files:
        - src: "./dist"   # 빌드된 React 앱의 dist 폴더를 복사
          dest: "/app/build"  # Nginx 컨테이너의 /app/build 경로에 복사
    - name: "nginx-config"  # 두 번째 레이어는 Nginx 설정 파일
      files:
        - src: "./nginx.conf"  # 호스트 머신의 nginx.conf 파일을 복사
          dest: "/etc/nginx/conf.d/default.conf"  # 컨테이너의 Nginx 설정 경로에 복사

